<?php

/**
 * @author	    Dirk Louwers	<dirk_louwers@hotmail.com>
 * @copyright	copyright (c) 	2005 Dirk Louwers
 */
$modversion['name'] = _MI_PROJECTS_NAME;
$modversion['version'] = 0.01;
$modversion['description'] = _MI_PROJECTS_DESC;
$modversion['author'] = 'Dirk Louwers';
$modversion['credits'] = 'for Adboma Projectdevelopment';
$modversion['help'] = 'projects.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/projects_slogo.png';
$modversion['dirname'] = 'reprojects';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'projects';
$modversion['tables'][1] = 'project_images';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Blocks
//$modversion['blocks'][1]['file'] = "headline.php";
//$modversion['blocks'][1]['name'] = _MI_HEADLINES_BNAME;
//$modversion['blocks'][1]['description'] = "Shows headline news via RDF/RSS news feed";
//$modversion['blocks'][1]['show_func'] = 'b_xoopsheadline_show';
//$modversion['blocks'][1]['template'] = 'xoopsheadline_block_rss.html';

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'list.html';
$modversion['templates'][1]['description'] = 'Displays a list of projects for the users to search through.';
$modversion['templates'][2]['file'] = 'view.html';
$modversion['templates'][2]['description'] = 'Allows for a detailed view of one of the projects';

$modversion['config'][1]['name'] = 'lid';
$modversion['config'][1]['title'] = '_MI_MAPID';
$modversion['config'][1]['description'] = '_MI_MAPIDDSC';
$modversion['config'][1]['formtype'] = 'textbox';
$modversion['config'][1]['valuetype'] = 'text';
$modversion['config'][2]['name'] = 'maptype';
$modversion['config'][2]['title'] = '_MI_MAPTYPE';
$modversion['config'][2]['description'] = '_MI_MAPTYPEDSC';
$modversion['config'][2]['formtype'] = 'select';
$modversion['config'][2]['valuetype'] = 'text';
$modversion['config'][2]['default'] = 'JAVA';
$modversion['config'][2]['options'] = ['JAVA' => 'Java', 'CGI' => 'Statisch'];
$modversion['config'][3]['name'] = 'country';
$modversion['config'][3]['title'] = '_MI_COUNTRY';
$modversion['config'][3]['description'] = '_MI_COUNTRYDSC';
$modversion['config'][3]['formtype'] = 'text';
$modversion['config'][3]['valuetype'] = 'text';
